
import { Silkscreen, Chakra_Petch } from "next/font/google";
import "./globals.css";

// components
// import Header from "@/components/Header";
// import PageTransition from "@/components/PageTransition";
// import StairTransition from "@/components/StairTransition";
import Home from "./page.jsx";

const silkscreen = Silkscreen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-silkscreen"
})
const chakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-chakra"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chakra.variable}>
        <Home />
          {/* <Header />
          <StairTransition />
          <PageTransition>{children}</PageTransition>
          <Analytics /> */}
      </body>
    </html>
  );
}