import { Geist, Geist_Mono, Chakra_Petch } from "next/font/google";

import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chakra = Chakra_Petch({
  variable: "--font-chakra",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${chakra.variable} antialiased`}
      >
        {/* <Header /> */}
        <div className="fixed top-0 left-0 w-full z-40 bg-[#1c1c22] bg-opacity-80 backdrop-blur text-white font-chakra transition-all duration-300 shadow-md">
          <Header />
        </div>
        <StairTransition />
        <PageTransition>{children}</PageTransition>
        {/* {children} */}
        <Analytics />
      </body>
    </html>
  );
}
